# apiVersion: v1
# kind: Service
# metadata:
#   name: django-service
# spec:
#   selector:
#     app: django-todo
#   ports:
#     - protocol: TCP
#       port: 8000
#       targetPort: 8000
#   type: ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: django-nginx-service
spec:
  type: NodePort
  selector:
    app: django-nginx-todo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 32002  # Optional: You can omit `nodePort` to let K8s assign one automatically
